name: SupplySign
main: redsgreens.SupplySign.SupplySign
version: 1.8.0
author: redsgreens
commands:
  supplysign:
    description: 'Used to reload data and list available SupplySign kits' 
    usage: '/supplysign <reload | listkits> (Used to reload data and list available SupplySign kits)'
website: http://dev.bukkit.org/server-mods/supplysign/
