#
# ShowErrorsInClient: toggle that determines if permissions or other error messages
#                     are displayed client-side
#
# Allowed values are: Yes (shows errors to players)
#                     No (errors only show up in server console)
# 
ShowErrorsInClient: Yes

#
# AllowNonOpAccess: if there is no permissions plugin loaded, then this setting 
#                   allows users without op status to access signs
#
# Allowed values are: Yes
#                     No
#
AllowNonOpAccess: No

#
# FixSignOnSignGlitch: this setting fixes the glitch where a player can place a sign 
#                      on another sign
#
# Allowed values are: SupplySignOnly (only fixes glitch for SupplySigns)
#                     Global (fixes glitch for all signs)
#                     Disabled (disables fix completely)
#
FixSignOnSignGlitch: SupplySignOnly
